### ISSUE TITLE
[Contacts] Improved workflow to create place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1260]
Based on feedback from initial testers, we want to streamline the process to create a place to include the creation of the primary contact. This is somewhat possible already if you select the "add new" as the primary contact, but needs the following improvements:
- Automatically set the Place name as `{{person_name}}'s family`
- Split the person name field into `First Name`, `Last Name`
- Additional fields for the person: `National ID Number`, `Alternate phone number`, `Date of Birth`

Given that these fields may change from one deployment to another it seems prudent to have a configurable solution, time permitting. One possibility would be that the whole contact creation process is just an XML form from which we can configure the person and place creation and assignment. 

_This may be related to #842._

**Comment by alxndrsn** [comment]
# Using Enketo to create contacts with arbitrary fields

This actually seems feasible.

## list of requested fields & their types (JSON)

Describe a db object type as JSON:

	{
		"type": "person",
		"title": "{{first.name}} {{last.name}}"
		"fields": {
			// an object or string can be provided for a field - string alone
			// represents only the data type; with an object you can supply
			// extra attributes such as validation (e.g. `required`)
			"first_name": {
				"type": "string",
				"required": true
			},
			"last_name": "string",
			"phone": "phone",
			"code": "string",
			"notes": "text",
			"location": "db:location"
		}
	}

* Field labels are derived as `$type.$field.name.replace('_', '.')`
* a field's `type` dictates how it is displayed both when editing/creating and also viewing the object.  `location` is a very special type - it stores the ID of a location.  When viewing, it will display the place's name and link to it in Contacts tab; when editing it will display the dropdown of locations

This configuration would be saved somewhere suitable for tech leads/admins to edit it.  TODO check where that is!
 
## xform

```xml
<h:html>
	<h:head>
		<h:title>{{New {{schema.type}} | translate}}</h:title>
		<model>
			<instance>
				<!-- TODO check the xforms spec to see why we have to name this node after
						the data type we're collecting.  If we could just call it something
						generic, then it would save a fair bit of effor when templating.
						It's also not clear what the `id` and `version` attribtes are used
						for, but neither of these seem of obvious use. -->
				<{{schema.type}} id="{{schema.type}}" version="{{timestamp}}">
					<!-- iterate over schema.fields to produce an empty element for each.
							Default values will be handled by passing initial data into
							`Enketo.Form`.  Follows an example of generated fields: -->
					<first_name/>
					<last_name/>
					<phone/>
					<code/>
					<notes/>
					<location/>
					<meta>
						<!-- TODO check in the xforms docs what this `meta` node is actually for.
								Current assumption is that these are fields which the user cannot
								edit directly.  Of course, they could still tamper with them
								quite easily. -->
						<!-- every example we have sets an isntanceID meta field.  This contains
								a UUID which is calculated at form load time (or perhaps supplied,
								when editing a form).  We could use it to track the document ID of
								forms we're editing, but for new forms, we might as well let pouch
								assign the ID. -->
						<instanceID/>
					</meta>
				</{{schema.type}}>
			</instance>
			<!-- here we set up bindings.  For our simple forms, this means:
					1. type-specific validations (e.g. `number`, `date` etc.)
					2. field-specific validations (e.g. `required` -->
			<bind nodeset="/{{schema.type}}/first_name" required="true()" type="string"/>
		</model>
	</h:head>
	<h:body> <!-- no class here - we won't be splitting into different pages -->
		<!-- iterate over the fields, and generate an input for each one.  `appearance
				will depend on the data type of the field. -->
		<input ref="/{{schema.type}}/first_name">
			<label>{{type + '.' + field.name.replace('_', '.') | translate}}</label>
		</input>
		...
		<input ref="/{{schema.type}}/location" appearance="dbObject" data-db-type="location">
			<label>{{type + '.' + field.name.replace('_', '.') | translate}}</label>
		</input>
	</h:body>
</h:html>
```

## enketo form

Handled by enketo/XSLT :-)

We would need to create a `dbObject` widget for Enketo which displays a drop-down selecter.  To populate the dropdown, use `_view/doc_by_type` with startkey/endkey to filter for a specific `type` value.

## save to doc with type `person` - `xml2json()`

We already have code in the `EnketoService` for converting form data in XML to JSON.  We could re-use this code.

## on saving, display the newly-created contact

**Comment by alxndrsn** [comment]
```
TASKS
[ ] allow configuration of person (& other?) contact types through admin UI
[ ] create dbObj enketo widget
[ ] create enketo form XML from JSON config
[ ] join the dots

**Comment by alxndrsn** [comment]
# TODO

## Sort out visual differences in Contact forms:

For each example, current version is shown first; expected version is shown second.

### Small screen:
<img width="1280" alt="screen shot 2015-09-23 at 14 00 48" src="https://cloud.githubusercontent.com/assets/191496/10044472/a2a35322-61fb-11e5-937c-7d8464894869.png">
<img width="1280" alt="screen shot 2015-09-23 at 14 00 49" src="https://cloud.githubusercontent.com/assets/191496/10044473/a2a667d8-61fb-11e5-9dc3-aeccea1558a6.png">

### Big screen:
<img width="1280" alt="screen shot 2015-09-23 at 14 00 59" src="https://cloud.githubusercontent.com/assets/191496/10044474/a2a7374e-61fb-11e5-9b85-f4a7d8abbefa.png">
<img width="1280" alt="screen shot 2015-09-23 at 14 01 00" src="https://cloud.githubusercontent.com/assets/191496/10044475/a2a93eb8-61fb-11e5-911b-2048aba75ebe.png">

**Comment by garethbowen** [comment]
### Code review

- [ ] Improve naming. There are classes named `N` and `X` which mean nothing to me.
- [ ] Use `$translate` instead of `translateFilter`. I know the existing code uses both, but using the service feels more correct to me than using the filter. `$translate` has an `instant` to do sync translations.
- [ ] Avoid string concatenation where possible, eg: xml generation. It's too hard to read, and too easy to miss a closing bracket or forget to escape something. There are probably libraries to generate XML in Javascript if the browser functions are insufficient. This may be obsolete if we decide to have users provide the form XML instead of generating it from JSON.
- [ ] Remove one or other of the facility widgets.
- [ ] Avoid `$scope.$apply()` if possible - it's a common cause of issues. If you use `$q` for promises it should update the UI without needing `$scope.$apply()`. This is definitely an annoying part of angular.
- [ ] Always use `$q` instead of `Promise`. They are functionally equivalent but `$q` reduces the need for `$scope.$apply`.

Generally try and reduce the length and nesting in functions for readability. For example the `saveDoc` function in `EditContactCtrl` is 50 lines long and has up to 3 nested promises. Pulling some of the nested promises out as separate functions would make it easier to read and potentially make it easier to reuse parts.

Overall, good work!

**Comment by alxndrsn** [comment]
I think this ticket has served its purpose.  Lots of things spun off from it, and we've created a lot of tech debt (hopefully reinvested for profit elsewhere).

**Comment by abbyad** [comment]
Overall works very well. Any issues discovered later will be opened in new issues. Moving to Ready.
