### ISSUE TITLE
Meta issue: Restricted user cannot see contacts or reports on fresh browser

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1341]
If you start with a fresh browser with a restricted user that previously had access to reports & contacts items, no contacts or reports are seen.

If an admin in a separate browser updates the contact then the contact become visible by the restricted user. This may be related to #1006 and #1303.

**Comment by browndav** [comment]
I've observed this issue in my local development environment and on `lg.dev`.

**Comment by garethbowen** [comment]
I get a pouchdb error about a minute after logging in to lg.dev with a restricted user. I suspect the replication is failing. Possibly the connection is timing out?

**Comment by garethbowen** [comment]
Reloaded a few times, and waited a while, and it worked.

**Comment by garethbowen** [comment]
I've added a changes listener to the Contacts tab so it'll be more obvious when it works.

However reports are still not showing up for the "demo" user on lg.dev so I'm still working on it.

**Comment by garethbowen** [comment]
Reports are not being replicated because currently filtered replication only allows reports _submitted by_ contacts in your hierarchy. This should be changed to only allow reports _submitted regarding_ contacts in your hierarchy.

**Comment by garethbowen** [comment]
The workaround for the demo is to submit report from the same user you want to use to view them. Deprioritising for now.

**Comment by browndav** [comment]
Should work for now, thanks.

**Comment by abbyad** [comment]
I cannot see any data with restricted user on the Tecno Y4 using our app or Chrome 45.

The general app structure loads properly, but the forms, contacts, data are not loaded.

**Comment by browndav** [comment]
Thanks, I'll test/debug.

**Comment by abbyad** [comment]
I am still encountering this problem. Previously, with my tests on the Y4 the data showed up about 5 hours later but I started with a fresh browser yesterday, logged in as a restricted user (demo on lg.dev) and have not seen any data (reports, contacts) loaded yet. 
I do see the same error as @garethbowen mentioned in Console:
```
Uncaught (in promise) 
{
  status: 500, 
  name: "unknown_error", 
  message: "Database encountered an unknown error", 
  error: true, 
  result: Object
}
```
Is there a way to trigger the database to download the data?

**Comment by browndav** [comment]
```json
doc_write_failures: 0
docs_read: 0
docs_written: 0
end_time: Wed Oct 21 2015 11:58:16 GMT-0700 (PDT)
errors: Array[1]
last_seq: 0
ok: false
start_time: Wed Oct 21 2015 11:57:45 GMT-0700 (PDT)
__proto__: Invalid Date
status: "aborting"
__proto__: Object
status: 500
```

Theory: PouchDB is refusing to even attempt replication if it has noticed that it's disabled on a previous request, and this happens regardless of URL (even if CORS wouldn't strictly be required in a proxied configuration).

- [ ] Try to figure out why our seemingly properly-configured CouchDB isn't serving CORS headers
- [ ] If we can't get CouchDB to serve CORS headers, patch `medic-api` to test the theory
- [ ] If patching medic-api works, consider reviewing/keeping the code from above

**Comment by browndav** [comment]
Found while investigating the issue, but doesn't appear to be in the critical path: https://github.com/pouchdb/pouchdb/issues/4501

**Comment by browndav** [comment]
We've verified that our browser requests aren't including the `Origin` header, which makes CouchDB decide not to serve the `Access-Control-Allow-Origin`; the CORS specification confirms this is correct. Investigate why we're not sending this header – we may be able to supply default XHR request headers via http://pouchdb.com/api.html#create_database.

**Comment by browndav** [comment]
Update: I forced an in-request `Origin` header via the `proxyReq` event listener in `medic-api`, which had the effect of forcing CouchDB to serve CORS headers for every proxied request. The replication problem remains. I suspect the whole CORS issue (which we were inferring from the `explainCors` warnings) may be a dead end caused by a broken tcheck in pouchdb/pouchdb#4501.

I'll go ahead and trace through the actual replication-invocation code today, while we're waiting for an upstream response.

**Comment by browndav** [comment]
Upstream confirmed that CORS messages were spurious: https://github.com/pouchdb/pouchdb/issues/4501. Update PouchDB and add some additional tracing to the replication paths to try to help narrow down the issue.

**Comment by browndav** [comment]
I managed to catch a `_changes` request (which AFAICT is essential to PouchDB's replication feature) taking two orders of magnitude longer with a `filter=` parameter than without it. Suspect we're timing out twenty-five seconds after calling PouchDB's `replicate` function, which kills the whole replication operation.

To do:
  - [ ] Reproduce the performance difference locally using a large, fragmented database
  - [ ] If not confirmed locally, investigate Medic OS or AWS-specific performance issues
  - [ ] If confirmed locally, see if we can avoid use of the `filter=` parameter
  - [ ] If confirmed locally, produce an isolated test case and report upstream

**Comment by garethbowen** [comment]
@browndav This is one of the requests you caught:

```
time curl -vvv 'https://admin:password@lg.dev.medicmobile.org/medic/_changes?timeout=25000&style=all_docs&heartbeat=1000&filter=medic%2Fdoc_by_place&id=6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E&since=0&limit=100&_nonce=1446076476156'
```

Did you copy that verbatim? The `since=0` bit doesn't look right as we always call pouch.changes with `since: 'now'` because we don't care about historical changes. I'm wondering if this is a red herring.

**Comment by browndav** [comment]
Update from Slack discussion: the `_changes` request is associated with PouchDB's replication implementation IIRC, and the `since` and `limit` fields are generally irrelevant in terms of overall performance. Increasing the instance size improved performance through parallelism, but not more than you'd expect from near-perfect scaling (about a 40% improvement, but still 30s). We also determined that there were a number of confounding factors/bugs on lg.app, so we're updating that today.

Proposed long-term solution: detect this request in medic-api, and route it to a function that applies the filter in-process as CouchDB sends us results. This will require pulling more data from CouchDB, but I suspect will be much more performant due to the removal of interpreter startup time (my best guess for what's going on with `couchjs`).

**Comment by browndav** [comment]
I'm seeing this working properly on every device I've tested with now, including Chromium 30 on the desktop, Chrome on the Y4, and the Chrome 30.0.0 Webview in our container app. I'd still like to look at why the server-side filters perform so poorly and see if we can fix/workaround that, but IMO we could spin that issue off.

Any objections to moving this on to code review and acceptance testing?

**Comment by browndav** [comment]
No objections noted, moving to code review.
