### ISSUE TITLE
LG ContactSchema

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1350]
1. When creating a contact, automatically set the Place name as `{{person_name}}'s family`
1. change name field to separate `First Name` and `Last Name` fields
1. additional fields for the person:
  - _National ID Number_: `string`
  - _Alternate phone number_: `phone`
  - _Date of Birth_: `date`

# TODO
- [x] make `name` field calculated if not explicitly a field
- [x] configure `ContactSchema` with LG-specific fields
- [x] add extra translations for LG-specific fields
- [x] when loading contact create form, check first if there is a saved form, e.g. `form:contact:person` or `form:contact:person:create`, and if there is then use that instead of generating a form
- [x] do the same as above for Editing a contact.  Allow the same form to be used for both (if no `:create` or `:edit` suffix is used), or different forms, or generated for edit and supplied for Create (this seems closest to what we want for LG)
- [x] add a demo contact/family Create form for LG
- [x] update demo Family form's data structures
  - [x] data model should be in the correct format to save Family and Person at the same time
  - [x] `family.name` should be a calculated field (only in English...at this stage!)
- [x] ponder how `person.parent` is going to get set!  This should probably be for the general case!
- [x] work out why new Family is not selected after the save
- [x] make sure phone number validation is working correctly

**Comment by abbyad** [comment]
Making @joshnesbit the acceptance tester here. @alxndrsn, he should also be able to help with field/design questions as well.

**Comment by alxndrsn** [comment]
# TODO
- [ ] make `name` field calculated if not explicitly a field

**Comment by alxndrsn** [comment]
@abbyad fulfillment of **2** and **3** is demoable.  **1** is more complicated with the current form/schema setup.

## Changes

### PERSON schema:
```js
var PERSON = {
  badge: 'fa-user',
  name: '{{first_name}} {{last_name}}',
  fields: {
    first_name: {
      type: 'string',
      required: true,
    },
    last_name: {
      type: 'string',
      required: true,
    },
    phone: {
      type: 'phone',
      required: true,
    },
    national_id_number: 'string',
    date_of_birth: 'date',
    alternate_phone: 'phone',
    notes: 'text',
    parent: 'custom:medic-place',
  },
};
```

### Extra translations:
```
person.field.first_name = First Name
person.field.last_name = Last Name
person.field.national_id_number = National ID Number
person.field.date_of_birth = Date of Birth
person.field.alternate_phone = Alternative Phone Number
```

**Comment by alxndrsn** [comment]
Have moved this back; hopefully we can discuss later today.

**Comment by alxndrsn** [comment]
https://github.com/medic/medic-projects/commit/ca5e95716692cd42bec88aaaebd561e15baf256c

**Comment by alxndrsn** [comment]
Works good on:
* `api` branch 1350
* `webapp` branch 1350
* this form: https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/family-modified.xml, uploaded as `contact:clinic:create`

**Comment by alxndrsn** [comment]
These changes are now all available on master, except for:
* the translations (on a branch of `api`)
* the LG config for ContactSchema (on a branch of `webapp`)
* the family form (in `projects`)

**Comment by garethbowen** [comment]
Looks good to me.

**Comment by abbyad** [comment]
Thanks @alxndrsn, this works well. Moving to Ready.

**Comment by alxndrsn** [comment]
:+1:
