### ISSUE TITLE
 move contact edit/create form from modal dialog into right-pane

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1364]
Separated from #1260 

---

## TODO
- [x] move the forms to RHS
- [x] make _Add Place_ work even if we already have `ContactContentCtrl` displayed
- [x] fix the CSS so it looks nice (this may just be DOM changes to be consistent with other RHS content(?))
- [x] when window is thin, RHS is hidden instead of LHS:

  > The `body` tag needs the `show-content` class which is triggered by `$scope.showContent`.  Trace that back to find the right way of setting it 

- [x] make sure Add Person link in ContactContent works
- [x] check if #1386 is fixed

**Comment by garethbowen** [comment]
Nice.
