### ISSUE TITLE
Rework behaviour of hardware back button, title bar back button, and Enketo back button

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1459]
From technical design work performed on today's 2015-10-19 milestone retrospective/planning call:

- [x] After #1415, each Enketo form should have a "close" button that looks like an `X`.
- [x] After #1460, hide the title bar's back button if and only if the user is filling out an Enketo form.
- [x] Ensure that the title bar back button and the hardware back button function identically.
- [x] Use `window.history.back()` for the Enketo `Previous` button, or omit it altogether if design says that's preferable.
- [ ] Confirm that the work on `select2` in #1395 works well with the above updates.

**Comment by browndav** [comment]
I think I got this right; please comment if anything looks wrong to you.

**Comment by alxndrsn** [comment]
## @abbyad
## Ref enketo CLOSE button

* where is it meant to go?  top right?  top left?  elsewhere?
* is there a suitable icon already, or should we really just use an `X`?
* should the user receive the standard enketo are-you-sure prompt?

**Comment by abbyad** [comment]
Using `fa-close`:

![image](https://cloud.githubusercontent.com/assets/789512/10616119/86d67106-7731-11e5-95f2-67c440c537f1.png)

What is the standard enketo "are-you-sure" prompt?

**Comment by alxndrsn** [comment]
The on implemented in #1415

**Comment by abbyad** [comment]
Oh, is it standard already?

The wording may be slightly different, but we can manage with the same generic text to cover both situations. Something like:
"You are navigating away from this unsaved form. Do you want exit and lose all entered data? Yes / No"

**Comment by browndav** [comment]
What's this blocked on?

**Comment by alxndrsn** [comment]
@browndav blocked by #1415

**Comment by alxndrsn** [comment]
I think it's #1395's responsibility to make sure it's working with `back` - nothing non-standard is done by this ticket.

**Comment by alxndrsn** [comment]
N.B. new behaviour of title bar back button does not always make sense, e.g. pressing `back` when viewing a contact that has just been created will take user back to the Contact Create form.  This feels a bit weird.
