### ISSUE TITLE
Refactor Settings and Cache services

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1526]
We have Settings and Cache services which are callback based, and a SettingsP service which is promise based with an event on change.
### Callbacks

Callbacks don't work well when mixed with promises, particularly in relation to updating the angular scope. As we use promises more this becomes more of an issue. Mixing callbacks and promises also leads worse code style than using either exclusively. Possibly we can solve these issues by including a $scope.$apply within the service.
### Promises

You can't resolve promises twice, so they don't work for emitting changes when the cache is invalidated. You can add an event listener registration function to the returned promise and use that instead, but the [current implementation](https://github.com/medic/medic-webapp/blob/develop/static/js/services/settings.js#L66-L73) of this is [buggy](https://github.com/medic/medic-webapp/commit/f2362afe1682608b9781e0d91f69357c66936a60). It's also non-standard.
### Event Emitters

Event Emitters might end up just a pretty version of callbacks, but it's worth investigating.
## Our Use Cases
1. Give me the current configuration. Ideal when performing a short lived action, for example: saving a report.
2. Let me know when the configuration changes. Ideal when updating a UI element based on configuration, for example: permissions.
## Tasks
- [ ] Implement a pattern which solves both use cases and can be used in clean and readable code.
- [ ] Refactor all uses of Settings and Cache services to use the new pattern.
- [ ] Remove the SettingsP service in favour of the one true Settings service.

**Comment by garethbowen** [comment]
This pattern should also be applied to the TaskGenerator service.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
@garethbowen is this one still relevant? If so, I'd say we could mark as scheduled and save for later - I'm assuming it's on the prioritized list of tech debt somewhere.

**Comment by garethbowen** [comment]
It's a nice to have. It's certainly not blocking us and would be far down the technical debt priority list I imagine. I vote we close for now, but I'll leave if for you to judge.

**Comment by sglangevin** [comment]
Sounds good. I'll close for now and we can re-open in the future if it moves up the tech debt priority list.
