### ISSUE TITLE
Move audit docs to a new database

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1864]
# TODO

- [x] save new audit docs to a separate db
- [x] create the audit db on api startup if it doesn't exist
- [x] add migration to move old audit docs to the audit db
- [x] make `audit_records_by_doc` view available in audit db's design doc

**Comment by mandric** [comment]
We should also consider not auditing ddocs or _local docs in medic-api.

**Comment by btbonval** [comment]
Hi, I'm Bryan, and I approve this issue!

**Comment by SCdF** [comment]
Also, as much as I trust Gareth, let's double-check that replication-based changes (as in what restricted users are doing) is audited properly.

**Comment by garethbowen** [comment]
It'd be great to have an e2e test for this as it's really easy to break. Currently all the e2e tests are run as admin because it's much easier to write a test when the data is up to date, rather than having to wait for replication to complete with every interaction, but if you can find a way to test a restricted user that would be awesome.

**Comment by SCdF** [comment]
@garethbowen this comes back to having a smaller controlled e2e database right? If you have an empty db (as in, you literally delete the DB and start again for the e2e tests, no history no nothing), would waiting for replication be less of an issue?

**Comment by garethbowen** [comment]
Not really. Currently some of the tests do setup by adding docs (app settings in particular) directly to the remote server, then loading the page. We would have to ensure the replication finishes, then reload the page, to ensure we're testing the settings we pushed. Furthermore replication is completely disabled in e2e testing, because protractor waits for all requests to finish, including longpoll replication requests.

This is particularly hard with auditing because it has to occur on the server you can only test it by replicating and then checking the audit log. So we're a little way away from being able to e2e test this.

In the meantime we could pull out the replication code into a unit, and unit test it.

**Comment by SCdF** [comment]
So yes: replication based changes are audited. I changed a contact and watched the couchdb logs, and got these useful lines:

```
[info] [<0.376.0>] OS Process #Port<0.3199> Log :: User 'admin' changing document '7845cd65c6f1f891fbd4d54e7bca1c1b'
[info] [<0.376.0>] OS Process #Port<0.3199> Log :: User 'lgdemo' changing document 'BD57F472-7599-E45E-9EA2-8CCC8D8251A2'
[info] [<0.376.0>] OS Process #Port<0.3199> Log :: User 'admin' changing document '56f5e2a7b035d1618d7707c5d101650f'
[info] [<0.390.0>] OS Process #Port<0.3260> Log :: User 'admin' changing document '56f5e2a7b035d1618d7707c5d1f0e7f7'
```
_(other lines removed for brevity)_

The first line is the audit doc for the contact, the second is the contact, and the third and forth are audit histories that I don't exactly understand yet, but were triggered because I saved a file.

**Comment by SCdF** [comment]
Hey @garethbowen we should have a chat about this: it seems more complicated than we'd hoped and I'd like to pick your brain on it

**Comment by SCdF** [comment]
Things left to do:

- [ ] Write unit tests for the migration. It's been tested, but there are no automated tests
- [ ] Make the changes to couchdb-audit more universally useful than what I've done to get it working for us.

**Comment by SCdF** [comment]
Hey @alxndrsn could take a look at a look at the following PR: https://github.com/medic/medic-api/pull/45

Specifically, at the migration script.

**Comment by SCdF** [comment]
Things to do:

- [ ] get medic-api changes reviewed and merged
- [ ] get couchdb-audit changed reviewed
- [ ] create a new release of couchdb-audit with changes, point medic-api at it
- [ ] get removal of couchdb-audit from medic-webapp reviewed
- [ ] merge above and update api submodule reference
