### ISSUE TITLE
Release 2.6.2

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2240]
### Release steps

* [x] Update Changes.md
* [x] Update app version (kanso.json, package.json, npm-shrinkwrap.json)
* [x] Merge to `testing`
* [x] Update lg.dev to 2.6.2.beta and run acceptance testing
* [x] Merge `testing` to `v2`
* [x] Tag the release in github
* [x] Update the app on lg-testing.app to the released version; perform sanity checks (verify app starts properly, syncs data, each tab appears functional)
* [ ] Update the app on the lg production server to the released version.

### Issues to include

* [x] PouchDB service pack #2166
* [x] Values not selected when editing CHP area #2223 
* [x] No blank option in CHP area drop-downs #2227 
* [x] Cannot edit some contacts #2199 #2235 
* [x] Create an all-in-one user/user-settings/contact addition API #2046
* [x] allow-new appearance in Enketo doesn't make the "New" option appear #2251 (need to confirm if this affects the beta)
* [x] Fix form type filter #1409

**Comment by SCdF** [comment]
@garethbowen: I didn't merge yet cause I wanted to make sure you're happy with what I merged, but here is my solution: https://github.com/medic/medic-webapp/issues/2247

**Comment by abbyad** [comment]
Can we add #1409 to the list? I am not the fix on 2.6.2-beta.3219, so I imagine it needs to be brought in explicitly.

**Comment by SCdF** [comment]
#2256 should also be added, it should increase performance for a bunch of admin tasks

**Comment by garethbowen** [comment]
2.6.2 got released but we found a blocker before rolling out to production. This will be fixed in 2.6.3.
