### ISSUE TITLE
Release 2.6.3

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2291]
### Release steps

* [x] Update Changes.md
* [x] Update app version (kanso.json, package.json, npm-shrinkwrap.json)
* [x] Merge to `testing`
* [x] Update lg.dev and run acceptance testing
* [x] Merge `testing` to `v2`
* [x] Tag the release in github
* [x] Update the app in testing to the released version; perform sanity checks (verify app starts properly, syncs data, each tab appears functional)
* [x] Update the app in production where applicable

### Issues to include

* [x] Pouch patch to record seq better #2288
* [x] Tasks and targets not working (console not defined) #2277
* [x] Snackbar showing all the time #2306 
* [x] Support external_id property on user-settings docs #2310
