### ISSUE TITLE
Upgrade to couchdb v2

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2854]
Meta issue for upgrading to couchdb v2.
- [x] #2855 Make migrations compatible with CouchDB 2.0
- [x] #2856 Replace uses of _config with couchdb v2 compatible api
- [ ] #2857 Update medic-os to couchdb v2
- [x] #2930 Update any README.md instructions for CouchDB2.0
- [x] #2931 CouchDB2.0 API version check
- [x] #2932 Test Couch2PG with CouchDB2.0
- [x] #2933 Get Travis using CouchDB2.0
- [x] #2934 Determine and document CouchDB 1.6 -> 2.0 migration strategy
- [x] #2935 CouchDB2.0 and Lucene, does that all still work?
- [ ] #2960 Make sure Concierge and CouchDB2.0 work correctly together
- [x] #3187 Consider supporting both CouchDB1.x and 2.x in production

**Comment by garethbowen** [comment]
This follows on from #2840

**Comment by SCdF** [comment]
Created a bunch more tickets with things we need to check. Because this is Kind Of A Big Deal™ I'm not sure we should be progressively merging things into master this one time, so I've created a branch: https://github.com/medic/medic-webapp/tree/2854-couchdb-2.0

If people think this is stupid we can just merge into master as we go.

**Comment by SCdF** [comment]
This doesn't seem to be a priority right now, so I'm taking it off myself and no longer marking it as active.

**Comment by SCdF** [comment]
@garethbowen managed to confuse myself and get lost in a nest of branches: forgot to get anyone to review this. Can you take a look, it's adding support for migrations to handle both versions of CouchDB: https://github.com/medic/medic-api/pull/129

**Comment by SCdF** [comment]
OK. With the exception of Concierge (whatever _that_ is) I'm ready to merge this into master.

**Comment by SCdF** [comment]
I think I'm going to split validate_doc_update into two, one on `medic` and the other on `medic-client`, the former dealing with hierarchical permissions / auth and the latter dealing with document structure.

**Comment by SCdF** [comment]
So I'm going to check to make sure http://docs.couchdb.org/en/2.0.0/couchapp/views/joins.html still works, in 2.0, and if it does I'm going to merge all the things into master.

**Comment by SCdF** [comment]
Looks great. MERGED.

Skipping the acceptance testing ticket. There is nothing specific that we should AT on this ticket, that shouldn't come up either specifically on sub-tickets, or be wide-spread as part of standard testing.

**Comment by mandric** [comment]
Acceptance testing on this might be having another dev (or anyone with a local setup on 1.x) run through the upgrade process?
