### ISSUE TITLE
Clean up labels and translations (master issue)

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2888]
All of the items below relate to the labels and translations for the default version of the app, configured for SMS projects. Some are cleaning up minor UX issues in the titles, others are translations.

- [x] The default config should be for SMS projects. Therefore the labels should be: District — Branch — Area (NO households or families)
	The current places look to be: Branch — CHP Area — Family (w/ primary contact listed as: primary caregiver). 
![screen shot 2016-11-03 at 12 08 26](https://cloud.githubusercontent.com/assets/1675870/20059810/a5106fac-a500-11e6-9c84-18e59600e631.png)

	From this screenshot, Branches may be "districts" behind the scenes. This may be the fault of old demo data; let me know if I should change the place names manually.
![screen shot 2016-11-03 at 11 47 06](https://cloud.githubusercontent.com/assets/1675870/20059729/566e0ca6-a500-11e6-9d61-2c433cc3a910.png)

- [x] Per the point above, "family members" should be "People" at all levels

- [x] titles on all pages in mobile should be centered. 

- [x] missing label: “contact.type.place.edit”
![screen shot 2016-11-03 at 12 12 34](https://cloud.githubusercontent.com/assets/1675870/20059870/064d10cc-a501-11e6-83b2-8a2f1c214a54.png)

- [x] In the "add" title, include place type. e.g. “Add Area”
![screen shot 2016-11-03 at 11 46 04](https://cloud.githubusercontent.com/assets/1675870/20059586/9dd645dc-a4ff-11e6-8ca7-4f9334d189b1.png)

- [x] REQUEST: When automatically naming a place after the primary contact, is it possible to make the name possessive if followed by a place type? e.g. “Dianna’s Area” or “Dianna’s Family” It would make the app more readable. “Dianna Area” or “Dianna Family” is awkward. We’d only want to do this when automatically naming the place after a person, rather than entering a place’s name itself, like “Busia Branch.”

**Comment by diannakane** [comment]
Ref #2768

**Comment by abbyad** [comment]
For the last point (possessive place), that relates to the default creation forms list in https://github.com/medic/medic-webapp/issues/2828

**Comment by garethbowen** [comment]
@diannakane Is this a fresh install or did you upgrade an existing installation? Is this on a server or local? If on a server, what URL? Did you upload any configuration?

**Comment by sglangevin** [comment]
Based on what I've seen, this is from alpha.dev. I don't think any config has been uploaded there in a while, so I'm not sure what config is currently there. Do we have a default config file we can upload? Or at least a config file that matches what the dev team has been using for development? I believe alpha.dev is on either the latest or a very recent alpha version.

**Comment by garethbowen** [comment]
Ok. IIRC alpha.dev doesn't get blown away between updates so any configuration changes that have been made will stick which might explain the bugs Dianna is seeing.

**Comment by diannakane** [comment]
OK moving the last request pertaining to possessives over to issue #2828

**Comment by garethbowen** [comment]
Most of the translations were correct but the alpha.dev deployment was out of date. I fixed up some more here: https://github.com/medic/medic-webapp/commit/f0da73b36e5ea50908f862454dc4f1ec261bfd31

**Comment by garethbowen** [comment]
I think the "Add" title was another case of out of date translations as I couldn't get it to show so I've ticked it off. Please test again on a clean install.

**Comment by garethbowen** [comment]
PR for centering titles: https://github.com/medic/medic-webapp/pull/2908

**Comment by garethbowen** [comment]
@SCdF Review please!

**Comment by SCdF** [comment]
Like Christmas in… November, I guess!
