### ISSUE TITLE
Allow users to enter Bikram Sambat dates into Medic Collect forms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3405]
CHWs in Nepal who are using Medic Collect need to be able to enter dates in the local calendar. Currently, Medic Collect only supports the Gregorian calendar. Make it possible for CHWs to enter Bikram Sambat dates. This is needed for our Nepal deployments.

cc @ranjuts @bishwas-medic 

Related: #3404

**Comment by sglangevin** [comment]
More info from @ranjuts:
- Ideal: Option to enter date in Nepali Date (Bikram Sambat) format : DD/MM/YYYY or pick from calendar (display Bikram Sambat Calendar  in date picker)
- Could work with: 3 separate dropdowns for DD, MM (or name of month) and YYYY and webapp to recognize that as a valid date field (as opposed to integer fields only to be displayed within the particular report -- currently done this way)

**Comment by ranjuts** [comment]
Had a chat w Alex re this and here's the gist. @alxndrsn please add/correct if anything. 

**Best option in terms of LOE + usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display the name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार  if form language is Nepali). 

**Best option in terms of usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार etc if form language is Nepali). 
AND 
Pick from Bikram Sambat Calendar. User has the option to choose.

**Comment by garethbowen** [comment]
@alxndrsn Have you made any progress on this? It's marked as required for 2.13.0 but I assume all changes will be in medic-collect so it's not really tied to any medic-webapp release?

**Comment by alxndrsn** [comment]
Yes, progress is in progress, and no, it should not affect webapp releases.

**Comment by sglangevin** [comment]
Thanks for the update, @alxndrsn. @ranjuts was expecting to test this by end of July since the district that needs this plans to deploy in mid-August. Are we on track to hit that timeline?

**Comment by alxndrsn** [comment]
Yes, I think that's realistic.

**Comment by alxndrsn** [comment]
# TODO
- [ ] make sure that it's easy to enable BS dates for Nepali builds
- [ ] fix date off-by-one bug (maybe just a display problem?  Perhaps should not convert dates to GMT for display)
- [ ] make sure that appropriate parts of the android functionality are being loaded from the lib rather than added to collect core

**Comment by alxndrsn** [comment]
BS calendar is enabled **_PER BUILD_**.  This is currently adequate according to Nepal team.

There are no build flavours configured for Nepal collect builds that I can find, but to enable the date format when building, set the env var `BIKRAM_SAMBAT=true`.

**Comment by ngaruko** [comment]
Is this easily testable on test instances @sglangevin ?

**Comment by sglangevin** [comment]
You'll need a build of Medic Collect with the BS calendar enabled to test this. @alxndrsn did you create a test build? Or someone else needs to do that?

**Comment by alxndrsn** [comment]
I still don't know what projects this is required for, as none of the Nepal projects seem to have their configurations stored in git.  I can supply a test APK for anyone that requires it.

**Comment by sglangevin** [comment]
@ranjuts are there any Nepal projects for which we can test this? Perhaps we can do a build using some existing Medic Collect config but with the BS calendar enabled on the build so that we can test this.

**Comment by alxndrsn** [comment]
I've added an appearance of `bikram-sambat` - when you use this, you will get the BS datepicker regardless of the phone's locale.

**Comment by sglangevin** [comment]
Cool, thanks @alxndrsn. Assigning to myself for AT.

**Comment by sglangevin** [comment]
I added this appearance to the following collect form and I'm seeing the Gregorian calendar when I access the form in Collect. I tested using Collect v1.4.5.1131-standard.

```
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Delivery Report</h:title>
    <model>
      <itext>
        <translation lang="Bahasa Indonesia (Indonesian)">
          <text id="/d/review_without_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>.</value>
          </text>
          <text id="/d/bs:label">
            <value>-</value>
          </text>
          <text id="/d/c/NS:label">
            <value>Home, with no skilled birth attendant</value>
          </text>
          <text id="/d/c/F:label">
            <value>Facility</value>
          </text>
          <text id="/d/c/S:label">
            <value>Home, with a skilled birth attendant</value>
          </text>
          <text id="/d/c:label">
            <value>Where did the delivery take place?</value>
          </text>
          <text id="/d/id:label">
            <value>Pasien ID</value>
          </text>
          <text id="/d/review_with_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>, with date of birth noted.</value>
          </text>
          <text id="/d/d:jr:constraintMsg">
            <value>-</value>
          </text>
          <text id="/d/d:label">
            <value>How many days since the delivery?</value>
          </text>
        </translation>
        <translation lang="हिन्दी (Hindi)">
          <text id="/d/review_without_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>.</value>
          </text>
          <text id="/d/bs:label">
            <value>-</value>
          </text>
          <text id="/d/c/NS:label">
            <value>Home, with no skilled birth attendant</value>
          </text>
          <text id="/d/c/F:label">
            <value>Facility</value>
          </text>
          <text id="/d/c/S:label">
            <value>Home, with a skilled birth attendant</value>
          </text>
          <text id="/d/c:label">
            <value>Where did the delivery take place?</value>
          </text>
          <text id="/d/id:label">
            <value>मरीज का ID</value>
          </text>
          <text id="/d/review_with_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>, with date of birth noted.</value>
          </text>
          <text id="/d/d:jr:constraintMsg">
            <value>-</value>
          </text>
          <text id="/d/d:label">
            <value>How many days since the delivery?</value>
          </text>
        </translation>
        <translation default="true()" lang="English">
          <text id="/d/review_without_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>.</value>
          </text>
          <text id="/d/bs:label">
            <value>When was the birth?</value>
          </text>
          <text id="/d/c/F:label">
            <value>Facility</value>
          </text>
          <text id="/d/c/S:label">
            <value>Home, with a skilled birth attendant</value>
          </text>
          <text id="/d/c:label">
            <value>Where did the delivery take place?</value>
          </text>
          <text id="/d/d:label">
            <value>How many days since the delivery?</value>
          </text>
          <text id="/d/id:label">
            <value>Patient ID</value>
          </text>
          <text id="/d/review_with_days:label">
            <value>Submitting delivery report for ID <output value=" /d/id "/>. Delivered at <output value=" /d/c_label "/>, with date of birth noted.</value>
          </text>
          <text id="/d/d:jr:constraintMsg">
            <value>The value must be between 0 and 365 days</value>
          </text>
          <text id="/d/c/NS:label">
            <value>Home, with no skilled birth attendant</value>
          </text>
        </translation>
      </itext>
      <instance>
        <d delimiter="#" id="d" prefix="J1!d!" version="2017-09-14 15-51">
          <id/>
          <c/>
          <d/>
          <bs/>
          <c_label/>
          <review_with_days/>
          <review_without_days/>
          <meta>
            <instanceID/>
          </meta>
        </d>
      </instance>
      <bind nodeset="/d/id" required="true()" type="string"/>
      <bind nodeset="/d/c" required="true()" type="select1"/>
      <bind constraint=". &gt;= 0 and . &lt;= 365" jr:constraintMsg="jr:itext('/d/d:jr:constraintMsg')" nodeset="/d/d" type="int"/>
      <bind nodeset="/d/bs" type="date"/>
      <bind calculate="jr:choice-name( /d/c , ' /d/c ')" nodeset="/d/c_label" type="string"/>
      <bind nodeset="/d/review_with_days" readonly="true()" relevant="../d &gt;= 0" type="string"/>
      <bind nodeset="/d/review_without_days" readonly="true()" relevant="not(../d &gt;= 0)" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/d/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <input appearance="numbers" ref="/d/id">
      <label ref="jr:itext('/d/id:label')"/>
    </input>
    <select1 appearance="quick" ref="/d/c">
      <label ref="jr:itext('/d/c:label')"/>
      <item>
        <label ref="jr:itext('/d/c/F:label')"/>
        <value>F</value>
      </item>
      <item>
        <label ref="jr:itext('/d/c/S:label')"/>
        <value>S</value>
      </item>
      <item>
        <label ref="jr:itext('/d/c/NS:label')"/>
        <value>NS</value>
      </item>
    </select1>
    <input ref="/d/d">
      <label ref="jr:itext('/d/d:label')"/>
    </input>
    <input appearance="bikram-sambat" ref="/d/bs">
      <label ref="jr:itext('/d/bs:label')"/>
    </input>
    <input ref="/d/review_with_days">
      <label ref="jr:itext('/d/review_with_days:label')"/>
    </input>
    <input ref="/d/review_without_days">
      <label ref="jr:itext('/d/review_without_days:label')"/>
    </input>
  </h:body>
</h:html>
```

**Comment by alxndrsn** [comment]
Added to master - please retest with new collect build when it becomes available.

**Comment by sglangevin** [comment]
Working well in version 1.4.5.1133 of Collect using the demo form for date input. Moving to ready.
