### ISSUE TITLE
Update top navigation bar on desktop and mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3660]
Relevant section of design spec: https://docs.google.com/document/d/1c-silPsrR92opiQaGU05te8MzsFnUjYCPUpsi2Vo9Vc/edit#bookmark=id.qityfo7awhp6

The Home tab will be added in another issue. This issue is focused on updating the size and styling of the top navigation bar and adding labels to the top nav on mobile.

On mobile:
- [ ] top black bar should be 52px tall
- [ ] top colored bar should be 38px tall
- [ ] add text labels below icons, H5 size (14 px) and bold. Light grey color if inactive (#D1D3D4), black if active (#333333)
- [ ] increase size of FontAwesome icons to 22.4px. Light grey color (#BCBEC0) if inactive, or black if active (#333333)
- [ ] make hamburger menu light grey (#BCBEC0) when inactive, to match other icons
- [ ] adjust width of tabs to make space for 4 tabs across

On tablet/desktop:
- [ ] top black bar should be 65px tall
- [ ] top colored bar should be 55 pm tall
- [ ] text labels are the same size as on mobile, H5 (15 px) and bold
- [ ] increase size of FontAwesome icons to 26px. Light grey color (#BCBEC0) if inactive, or black if active (#333333).

**Comment by sglangevin** [comment]
Closing this as we have a new design for the top bar that will be implemented in 3.1.
