### ISSUE TITLE
Spike: Deployment containerization

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3983]
Investigate and implement a containerization solution which means our stack can run safely on a range of OSes and multiple deployments can run on the same instance. The end result is to better support a project self-hosting the deployment, and to save money on deployment by combining some or all of our AWS instances.

One possible route is to use Docker but there are others out there so we need to know the pros and cons of each to determine which is right for us.

**Comment by browndav** [comment]
**To-do list**

- [ ] Test existing chroot image interactively inside of an `ubuntu:16.04` image, using the `initrd/common/boot/container-start` script as an entry point.
- [ ] Fix any issues with the `container-start` script. Some are likely to exist, due to differences between chroot and container environments/privileges.
- [ ] Write a `Dockerfile` that overlays the chroot tarball on to `ubuntu:16.04` using `ADD`. Use `container-start` as an `ENTRYPOINT`.
- [ ] Use Docker `VOLUME`s for `$ROOT/srv/storage` and `$ROOT/srv/settings`; make changes to the `container-start` script if necessary for support.
- [ ] Experiment with Docker networks and port mapping; determine which features we need to use and how to support them.
- [ ] Demo a working `Dockerfile`, stored at the root of the `medic-os` repository, that boots up and says hello to a web browser.

**Comment by browndav** [comment]
Successful `docker build` and `docker run` of `medic-os:alpha` this morning with CouchDB v1.7.0. All services start properly. Will write up directions today and consider how best to integrate Docker into automated builds.

**Comment by SCdF** [comment]
@browndav gardener or horti?

**Comment by browndav** [comment]
Still gardener; let me file an issue for horti integration. Looks like the packages already exist and work, so this shouldn't be a huge deal to do.

**Comment by browndav** [comment]
Moving to acceptance testing. We'll send an e-mail around to do a demo/walkthrough and figure out how to best code review this sort of thing.
