### ISSUE TITLE
[pouch] bulk-fetching docs by ID is very slow

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4167]
# TODO

- [x] `master`
- [x] `2.14.x` — https://github.com/medic/medic-webapp/pull/4183
- [ ] `2.13.x` — https://github.com/medic/medic-webapp/pull/4188
- [ ] `2.12.x` — https://github.com/medic/medic-webapp/pull/4187

# Steps to recreate

1. browse to http://localhost:8080/atp/pouchdb-6.1.2/ (or other pouch version)
2. execute the following code:

```
user = ?;
localDbName = ?; // re-use this to prevent re-replication every iteration
db = new PouchDB(localDbName);

db.replicate.from(`http://${user}:pass@localhost:5988/medic`, {
    doc_ids: [`org.couchdb.user:${user}`],
    timeout: 1000*60*10,
  })
  .then(() => console.log('db replication complete.'))
  .then(() => benchmark(db))
  .then(() => benchmark(db, { worker:'worker' }))
  .catch(console.log);

function benchmark(db, opts) {
  if(!opts) opts = {};
  opts.include_docs = true;

  const allDocsStart = Date.now();
  let allIds;

  return db.allDocs(opts)
    .then(res => {
      console.log(`[worker: ${opts.worker}] DONE: allDocs`, Date.now() - allDocsStart, 'ms');
      allIds = res.rows.map(r => r.id);
    })
    .then(() => {
      const manualStart = Date.now();
      return db
        .allDocs(opts)
        .then(res => res.rows.filter(row => allIds.includes(row.id)))
        .then(() => console.log(`[worker: ${opts.worker}] DONE: manual`, Date.now() - manualStart, 'ms'));
    })
    .then(() => {
      const filteredStart = Date.now();
      opts.keys = allIds;
      return db
        .allDocs(opts)
        .then(() => console.log(`[worker: ${opts.worker}] DONE: filtered`, Date.now() - filteredStart, 'ms'));
    });
}
```

# Results

## Pouch `6.1.2`
```
DONE: allDocs 560 ms
DONE: manual 1348 ms
DONE: filtered 370821 ms
```

## Pouch `6.4.2`
```
DONE: allDocs 544 ms
DONE: manual 6184 ms
DONE: filtered 2759 ms
```

**Comment by alxndrsn** [comment]
Fixed in https://github.com/pouchdb/pouchdb/issues/6854.  Upgrade _all_ projects to 6.4.x immediately.

**Comment by garethbowen** [comment]
Merged to master. Not backported yet. Might be worth doing some extensive testing on alpha before backporting.

**Comment by alxndrsn** [comment]
A couple of notes:
* it looks like we need to supply `options.timeout` for `DB().replicate(…)` in `services/db-sync.js` with this latest PouchDB version
* above benchmarks were performed _without `include_docs: true`_, and should be re-run with that flag passed

**Comment by garethbowen** [comment]
@alxndrsn We do supply a `options.timeout: false` [in DbSync](https://github.com/medic/medic-webapp/blob/master/static/js/services/db-sync.js#L44). If it's timing out it might be a PouchDB bug?

**Comment by alxndrsn** [comment]
Thanks - very possibly a regression in PouchDB - manually setting `options.timeout` to a Very Big Number works.

**Comment by garethbowen** [comment]
@alxndrsn I've merged your PR to 2.14.x but given your comments above won't we also need to set `options.timeout`? I've just tested it locally on alpha and I can't see the changes request timeout. Can you confirm the regression?

**Comment by alxndrsn** [comment]
![screen shot 2018-02-13 at 11 00 07](https://user-images.githubusercontent.com/191496/36144029-13c5fcd2-10ad-11e8-8584-5e98a35f7032.png)

^^ changes feed requests no longer timing out.  I'm not sure what was causing this before, but we should keep an eye on it when acceptance testing.

**Comment by alxndrsn** [comment]
This still needs checking.

**Comment by alxndrsn** [comment]
Timeout bug worked around in #4215.

**Comment by alxndrsn** [comment]
All PRs code reviewed separately.

**Comment by ngaruko** [comment]
Can you advise on how to AT this @alxndrsn ?

**Comment by alxndrsn** [comment]
Simplest is to compare app startup times for a fully-synched client from before and after this patch.
